### ISSUE TITLE
Pinning CPU at 100% or Pinning cores to 100%

### ISSUE THREAD

**Issue by DrTHC** [avi12/youtube-time-manager-feedback#15] opened 2024-02-03 15:59 UTC
### Describe the bug

Your app is pinning my I9 9900k overclocked at 100%. I have spend a while troubleshooting why my edge was making my entire pc feel sluggish. After a while I removed your application and my usage went back to 2-3% with a max spike of around 15%. I also caught sw.js (youtubes renderer) using 14gb ram last night. Again since removal of your application I have had no problems. 

### How to reproduce

Just run the browser for a bit and it will start to bloat the system down. 

### Expected behavior

Bloating system, Filling RAM, using a constant stream of processor power. 

### What browser(s) can you reproduce the issue on?

Chromium Edge

### What OS does it occur on?

Windows

### What's the extension version you're running?

N/A

### Make sure the bug wasn't reported before

- [X] I'm the first one to [report](/avi12/youtube-time-manager-feedback/issues?q=is%3Aissue+) it

### Make sure that YouTube Time Manager is the only extension running on YouTube

- [X] The issue still persists after disabling any other YouTube extension

### Additional context

I disabled all my extensions and left your running and still the issue persisted. I have since moved to another time tracker and have had no problems.

**Comment by avi12** [comment] 2024-02-03 17:20
Duplicate of #13

**Closed as completed by avi12** 2024-02-03 17:20 UTC
Labels: bug

**Comment by avi12** [comment] 2024-02-03 17:22
I recommend using the [CWS](https://chromewebstore.google.com/detail/youtube-time-manager/fpoooibdndpjcnoodfionoeakeojdjaj) version instead of the Edge version as it's way faster to get the ext approved at CWS

**Comment by DrTHC** [comment] 2024-02-03 19:47
The CWS version was the one I was using.

**Comment by avi12** [comment] 2024-02-03 20:01
Please refer to [the comment](https://github.com/avi12/youtube-time-manager-feedback/issues/13#issuecomment-1925417647)

**Comment by avi12** [comment] 2024-02-19 10:25
@DrTHC Can you try out this version? I fundamentally changed how the tracking works
DL;DR. instead of accessing the storage multiple times per second, it saves to the storage every minute and in the meantime, it stores it in memory and broadcasts it to the other tabs
[youtube-time-manager-3.1.0.zip](https://github.com/avi12/youtube-time-manager-feedback/files/14329795/youtube-time-manager-3.1.0.zip)
