### ISSUE TITLE
Accounts to sync between devices

### ISSUE THREAD

**Issue by Niborian** [avi12/youtube-time-manager-feedback#17] opened 2024-02-13 09:21 UTC
### Is it a change to the extension's functionality or to the pop-up settings page?

Extension's functionality

### If the latter, please propose a new design on Figma or describe it as detailed as possible

Just someway to sync between one broswer and another, or if its added to mobile/ tablets to get more detailed view time

**Comment by avi12** [comment] 2024-02-13 09:34
Duplicate of #10

**Closed as completed by avi12** 2024-02-13 09:34 UTC
Labels: enhancement
